INFO:root:gpu device = cuda:0
Traceback (most recent call last):
  File "main.py", line 277, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 207, in create_run_ensemble
    model = Network(init_channels, train_dataset.n_classes, model_description[worker]['config']['n_conv_layers'], genotype)
KeyError: <darts_bohamiann.BohamiannWorker object at 0x7fd8c5e88dd8>
