Workingdir: /home/rkohli/aml-project/PC-DARTS
Started at Mon Sep  9 15:09:26 CEST 2019
Running job darts+bohb-model using 2 cpus per node with given JID 3241658 on queue meta_gpu-black
Experiment dir : eval-EXP-20190909-150938
Worker running
09/09 03:09:41 PM DISPATCHER: started the 'discover_worker' thread
09/09 03:09:41 PM WORKER: start listening for jobs
09/09 03:09:41 PM DISPATCHER: started the 'job_runner' thread
09/09 03:09:41 PM DISPATCHER: Pyro daemon running on 127.0.0.1:39215
09/09 03:09:41 PM DISPATCHER: discovered new worker, hpbandster.run_01.worker.metagpu5.18860140417889568576
09/09 03:09:42 PM HBMASTER: adjusted queue size to (0, 1)
09/09 03:09:42 PM DISPATCHER: A new worker triggered discover_worker
09/09 03:09:42 PM HBMASTER: starting run at 1568034582.0247886
09/09 03:09:42 PM WORKER: start processing job (0, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.32076298997460984, 'grad_clip_value': 8, 'initial_lr': 0.00011427599632020381, 'n_conv_layers': 3, 'optimizer': 'adad', 'scheduler': 'Plateau', 'weight_decay': 6.013686816571838e-05}
09/09 03:09:42 PM WORKER: registered result for job (0, 0, 0) with dispatcher
09/09 03:09:42 PM job (0, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (1, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.1856031795045917, 'grad_clip_value': 6, 'initial_lr': 0.0029014193072674746, 'n_conv_layers': 3, 'optimizer': 'adam', 'scheduler': 'Cosine', 'weight_decay': 1.2967733036818081e-05}
09/09 03:09:42 PM WORKER: registered result for job (1, 0, 0) with dispatcher
09/09 03:09:42 PM job (1, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (2, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.15827934648407097, 'grad_clip_value': 4, 'initial_lr': 0.00022757656832408024, 'n_conv_layers': 3, 'optimizer': 'sgd', 'scheduler': 'Exponential', 'weight_decay': 0.00010418908293137454, 'nesterov': 'True', 'sgd_momentum': 0.8708462222296255}
09/09 03:09:42 PM WORKER: registered result for job (2, 0, 0) with dispatcher
09/09 03:09:42 PM job (2, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (3, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.25601436321342824, 'grad_clip_value': 7, 'initial_lr': 3.645281343168102e-06, 'n_conv_layers': 3, 'optimizer': 'sgd', 'scheduler': 'Exponential', 'weight_decay': 0.0008871211921839854, 'nesterov': 'False', 'sgd_momentum': 0.6717033226363355}
09/09 03:09:42 PM WORKER: registered result for job (3, 0, 0) with dispatcher
09/09 03:09:42 PM job (3, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (4, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.24136998748902797, 'grad_clip_value': 7, 'initial_lr': 0.0006791883560930832, 'n_conv_layers': 6, 'optimizer': 'adam', 'scheduler': 'Cosine', 'weight_decay': 0.00026316232624227164}
09/09 03:09:42 PM WORKER: registered result for job (4, 0, 0) with dispatcher
09/09 03:09:42 PM job (4, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (5, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.2706431804824151, 'grad_clip_value': 7, 'initial_lr': 0.00043181570823202576, 'n_conv_layers': 3, 'optimizer': 'sgd', 'scheduler': 'Plateau', 'weight_decay': 6.86185977653426e-05, 'nesterov': 'False', 'sgd_momentum': 0.3103225512800755}
09/09 03:09:42 PM WORKER: registered result for job (5, 0, 0) with dispatcher
09/09 03:09:42 PM job (5, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (6, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.3010663272071845, 'grad_clip_value': 7, 'initial_lr': 0.0019174575927522152, 'n_conv_layers': 5, 'optimizer': 'adam', 'scheduler': 'Plateau', 'weight_decay': 1.4457352600365393e-05}
09/09 03:09:42 PM WORKER: registered result for job (6, 0, 0) with dispatcher
09/09 03:09:42 PM job (6, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (7, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.17385341116232111, 'grad_clip_value': 7, 'initial_lr': 6.737978598082537e-06, 'n_conv_layers': 6, 'optimizer': 'adad', 'scheduler': 'Cosine', 'weight_decay': 1.0261556362865477e-05}
09/09 03:09:42 PM WORKER: registered result for job (7, 0, 0) with dispatcher
09/09 03:09:42 PM job (7, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (8, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.11181108853114458, 'grad_clip_value': 8, 'initial_lr': 0.0012361863171622886, 'n_conv_layers': 4, 'optimizer': 'sgd', 'scheduler': 'Plateau', 'weight_decay': 0.00038078215330315254, 'nesterov': 'False', 'sgd_momentum': 0.11676466053034149}
09/09 03:09:42 PM WORKER: registered result for job (8, 0, 0) with dispatcher
09/09 03:09:42 PM job (8, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (9, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.0778790878997575, 'grad_clip_value': 5, 'initial_lr': 0.0003993356799754671, 'n_conv_layers': 5, 'optimizer': 'adam', 'scheduler': 'Cosine', 'weight_decay': 8.347423000068203e-05}
09/09 03:09:42 PM WORKER: registered result for job (9, 0, 0) with dispatcher
09/09 03:09:42 PM job (9, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (10, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.3837946066924795, 'grad_clip_value': 7, 'initial_lr': 0.07565872140268527, 'n_conv_layers': 3, 'optimizer': 'adad', 'scheduler': 'Exponential', 'weight_decay': 0.0005175614310181604}
09/09 03:09:42 PM WORKER: registered result for job (10, 0, 0) with dispatcher
09/09 03:09:42 PM job (10, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (11, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.38907476232020055, 'grad_clip_value': 8, 'initial_lr': 1.9342464726473005e-06, 'n_conv_layers': 5, 'optimizer': 'sgd', 'scheduler': 'Cosine', 'weight_decay': 6.136194758812598e-05, 'nesterov': 'True', 'sgd_momentum': 0.1121777010806472}
09/09 03:09:42 PM WORKER: registered result for job (11, 0, 0) with dispatcher
09/09 03:09:42 PM job (11, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (12, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.2632034100000347, 'grad_clip_value': 8, 'initial_lr': 0.007961998970773836, 'n_conv_layers': 4, 'optimizer': 'adam', 'scheduler': 'Plateau', 'weight_decay': 0.0008127156039748151}
09/09 03:09:42 PM WORKER: registered result for job (12, 0, 0) with dispatcher
09/09 03:09:42 PM job (12, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (13, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.3360608138149397, 'grad_clip_value': 7, 'initial_lr': 1.4241754729952415e-06, 'n_conv_layers': 6, 'optimizer': 'sgd', 'scheduler': 'Cosine', 'weight_decay': 0.0004407805347588687, 'nesterov': 'True', 'sgd_momentum': 0.44676870591130013}
09/09 03:09:42 PM WORKER: registered result for job (13, 0, 0) with dispatcher
09/09 03:09:42 PM job (13, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (14, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.0018902001810268576, 'grad_clip_value': 7, 'initial_lr': 0.00011405004765184212, 'n_conv_layers': 6, 'optimizer': 'sgd', 'scheduler': 'Plateau', 'weight_decay': 0.0008910361137209435, 'nesterov': 'False', 'sgd_momentum': 0.1524686537145632}
09/09 03:09:42 PM WORKER: registered result for job (14, 0, 0) with dispatcher
09/09 03:09:42 PM job (14, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (15, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.29075406469600595, 'grad_clip_value': 6, 'initial_lr': 0.018924185000392016, 'n_conv_layers': 3, 'optimizer': 'adad', 'scheduler': 'Plateau', 'weight_decay': 0.00039567877806612087}
09/09 03:09:42 PM WORKER: registered result for job (15, 0, 0) with dispatcher
09/09 03:09:42 PM job (15, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (16, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.15739373789485273, 'grad_clip_value': 6, 'initial_lr': 2.0844310331029892e-05, 'n_conv_layers': 3, 'optimizer': 'adad', 'scheduler': 'Cosine', 'weight_decay': 2.578346030215353e-05}
09/09 03:09:42 PM WORKER: registered result for job (16, 0, 0) with dispatcher
09/09 03:09:42 PM job (16, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (17, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.22992806831665444, 'grad_clip_value': 7, 'initial_lr': 0.01240052835019709, 'n_conv_layers': 4, 'optimizer': 'sgd', 'scheduler': 'Cosine', 'weight_decay': 1.1739716368924901e-05, 'nesterov': 'False', 'sgd_momentum': 0.18757270504146917}
09/09 03:09:42 PM WORKER: registered result for job (17, 0, 0) with dispatcher
09/09 03:09:42 PM job (17, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (18, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.08451202007631485, 'grad_clip_value': 7, 'initial_lr': 0.0177175721683701, 'n_conv_layers': 3, 'optimizer': 'adad', 'scheduler': 'Exponential', 'weight_decay': 0.00018144445260982511}
09/09 03:09:42 PM WORKER: registered result for job (18, 0, 0) with dispatcher
09/09 03:09:42 PM job (18, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:42 PM WORKER: start processing job (19, 0, 0)
09/09 03:09:42 PM gpu device = cuda:0
09/09 03:09:42 PM config = {'drop_path_prob': 0.29753881899269036, 'grad_clip_value': 7, 'initial_lr': 0.0018116426801531825, 'n_conv_layers': 3, 'optimizer': 'adam', 'scheduler': 'Plateau', 'weight_decay': 0.0004856063600516809}
09/09 03:09:42 PM WORKER: registered result for job (19, 0, 0) with dispatcher
09/09 03:09:42 PM job (19, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "darts-bohb.py", line 78, in compute
    model = Network(self.init_channels, self.n_classes, config.n_conv_layers, genotype)
AttributeError: 'dict' object has no attribute 'n_conv_layers'

09/09 03:09:43 PM DISPATCHER: Dispatcher shutting down
09/09 03:09:43 PM DISPATCHER: shut down complete
