INFO:hpbandster:DISPATCHER: started the 'discover_worker' thread
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start listening for jobs
INFO:hpbandster:DISPATCHER: started the 'job_runner' thread
INFO:hpbandster:DISPATCHER: Pyro daemon running on 127.0.0.1:37785
INFO:hpbandster:DISPATCHER: discovered new worker, hpbandster.run_1.worker.metagpu5.23566140462560589632
INFO:hpbandster:HBMASTER: adjusted queue size to (0, 1)
INFO:hpbandster:DISPATCHER: A new worker triggered discover_worker
INFO:hpbandster:HBMASTER: starting run at 1568415176.6555622
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (0, 0, 0)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 154, 'drop_path_prob': 0.11891612614012122, 'grad_clip_value': 4, 'initial_lr': 0.051058534207630984, 'lr_scheduler': 'Cosine', 'optimizer': 'adad', 'weight_decay': 5.583594921168484e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (0, 0, 0) with dispatcher
WARNING:hpbandster:job (0, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (0, 0, 1)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 196, 'drop_path_prob': 0.3707964167958982, 'grad_clip_value': 7, 'initial_lr': 0.004492406927808005, 'lr_scheduler': 'Cosine', 'optimizer': 'sgd', 'weight_decay': 0.00015633997308993355, 'nesterov': 'True', 'sgd_momentum': 0.7057758139459791}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (0, 0, 1) with dispatcher
WARNING:hpbandster:job (0, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (0, 1, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 82, 'drop_path_prob': 0.2090126024620422, 'grad_clip_value': 5, 'initial_lr': 0.002509294704832559, 'lr_scheduler': 'Exponential', 'optimizer': 'sgd', 'weight_decay': 0.000452157244869867, 'nesterov': 'False', 'sgd_momentum': 0.21466683537435888}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (0, 1, 0) with dispatcher
WARNING:hpbandster:job (0, 1, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (1, 0, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 167, 'drop_path_prob': 0.26611408467928344, 'grad_clip_value': 5, 'initial_lr': 0.05291102019463377, 'lr_scheduler': 'Exponential', 'optimizer': 'sgd', 'weight_decay': 5.29662235480168e-05, 'nesterov': 'True', 'sgd_momentum': 0.33294005854705544}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (1, 0, 0) with dispatcher
WARNING:hpbandster:job (1, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (1, 0, 1)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 128, 'drop_path_prob': 0.24899997902817728, 'grad_clip_value': 5, 'initial_lr': 0.01546596782973025, 'lr_scheduler': 'Cosine', 'optimizer': 'adad', 'weight_decay': 3.8144505089550885e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (1, 0, 1) with dispatcher
WARNING:hpbandster:job (1, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (2, 0, 0)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 233, 'drop_path_prob': 0.012696198623969446, 'grad_clip_value': 7, 'initial_lr': 0.026562364352395212, 'lr_scheduler': 'Exponential', 'optimizer': 'sgd', 'weight_decay': 0.0008563419105147409, 'nesterov': 'False', 'sgd_momentum': 0.23057788838783055}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (2, 0, 0) with dispatcher
WARNING:hpbandster:job (2, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (2, 0, 1)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 65, 'drop_path_prob': 0.12223763249116693, 'grad_clip_value': 4, 'initial_lr': 0.0015306543420399057, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 0.0007643771646071694}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (2, 0, 1) with dispatcher
WARNING:hpbandster:job (2, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (2, 1, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 70, 'drop_path_prob': 0.34028395686567625, 'grad_clip_value': 8, 'initial_lr': 0.005724363080022888, 'lr_scheduler': 'Exponential', 'optimizer': 'adad', 'weight_decay': 0.00010142165442192922}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (2, 1, 0) with dispatcher
WARNING:hpbandster:job (2, 1, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (3, 0, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 110, 'drop_path_prob': 0.36233497300788675, 'grad_clip_value': 5, 'initial_lr': 0.0033150873367637215, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 3.0754972859727284e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (3, 0, 0) with dispatcher
WARNING:hpbandster:job (3, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (3, 0, 1)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 141, 'drop_path_prob': 0.37586537646564533, 'grad_clip_value': 6, 'initial_lr': 0.0017213337045664146, 'lr_scheduler': 'Cosine', 'optimizer': 'adad', 'weight_decay': 0.00026917923907812284}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (3, 0, 1) with dispatcher
WARNING:hpbandster:job (3, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (4, 0, 0)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 132, 'drop_path_prob': 0.0796839571443885, 'grad_clip_value': 5, 'initial_lr': 0.058589733219076415, 'lr_scheduler': 'Exponential', 'optimizer': 'sgd', 'weight_decay': 0.0004391755606106218, 'nesterov': 'True', 'sgd_momentum': 0.842869426360698}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (4, 0, 0) with dispatcher
WARNING:hpbandster:job (4, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (4, 0, 1)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 251, 'drop_path_prob': 0.22269193597000916, 'grad_clip_value': 4, 'initial_lr': 0.006855552066665283, 'lr_scheduler': 'Cosine', 'optimizer': 'sgd', 'weight_decay': 0.0006139281954864483, 'nesterov': 'True', 'sgd_momentum': 0.8733884891550024}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (4, 0, 1) with dispatcher
WARNING:hpbandster:job (4, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (4, 1, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 226, 'drop_path_prob': 0.20902362848561662, 'grad_clip_value': 4, 'initial_lr': 0.0234282242324168, 'lr_scheduler': 'Cosine', 'optimizer': 'sgd', 'weight_decay': 3.3051959764400664e-05, 'nesterov': 'True', 'sgd_momentum': 0.5571344997679167}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (4, 1, 0) with dispatcher
WARNING:hpbandster:job (4, 1, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (5, 0, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 244, 'drop_path_prob': 0.32968184857859345, 'grad_clip_value': 6, 'initial_lr': 0.0010017657003778089, 'lr_scheduler': 'Cosine', 'optimizer': 'adad', 'weight_decay': 5.629433540541345e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (5, 0, 0) with dispatcher
WARNING:hpbandster:job (5, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (5, 0, 1)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 176, 'drop_path_prob': 0.25048739962377103, 'grad_clip_value': 6, 'initial_lr': 0.0017376579092199342, 'lr_scheduler': 'Exponential', 'optimizer': 'adad', 'weight_decay': 1.7597752929408963e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (5, 0, 1) with dispatcher
WARNING:hpbandster:job (5, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (6, 0, 0)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 118, 'drop_path_prob': 0.24058569894060367, 'grad_clip_value': 7, 'initial_lr': 0.006018442201603251, 'lr_scheduler': 'Cosine', 'optimizer': 'adam', 'weight_decay': 0.0006211198264608556}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (6, 0, 0) with dispatcher
WARNING:hpbandster:job (6, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (6, 0, 1)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 161, 'drop_path_prob': 0.3950468924204614, 'grad_clip_value': 5, 'initial_lr': 0.004444486186095599, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 1.2480353784470794e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (6, 0, 1) with dispatcher
WARNING:hpbandster:job (6, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (6, 1, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 244, 'drop_path_prob': 0.11463913786768712, 'grad_clip_value': 7, 'initial_lr': 0.004305792121680805, 'lr_scheduler': 'Cosine', 'optimizer': 'sgd', 'weight_decay': 1.4890422207229083e-05, 'nesterov': 'True', 'sgd_momentum': 0.336134187206838}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (6, 1, 0) with dispatcher
WARNING:hpbandster:job (6, 1, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (7, 0, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 214, 'drop_path_prob': 0.21866832038098508, 'grad_clip_value': 4, 'initial_lr': 0.0027540610857020873, 'lr_scheduler': 'Cosine', 'optimizer': 'adad', 'weight_decay': 0.00044256651381945403}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (7, 0, 0) with dispatcher
WARNING:hpbandster:job (7, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (7, 0, 1)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 195, 'drop_path_prob': 0.22760441511805207, 'grad_clip_value': 4, 'initial_lr': 0.008783317020924416, 'lr_scheduler': 'Exponential', 'optimizer': 'adad', 'weight_decay': 0.00038471136317338637}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (7, 0, 1) with dispatcher
WARNING:hpbandster:job (7, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (8, 0, 0)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 228, 'drop_path_prob': 0.3043524214185991, 'grad_clip_value': 8, 'initial_lr': 0.01553733378831666, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 2.6215099623637707e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (8, 0, 0) with dispatcher
WARNING:hpbandster:job (8, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (8, 0, 1)
INFO:root:Running config for 3.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 230, 'drop_path_prob': 0.13572809607781272, 'grad_clip_value': 5, 'initial_lr': 0.003401633728375852, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 3.6375932993268564e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (8, 0, 1) with dispatcher
WARNING:hpbandster:job (8, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (8, 1, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 97, 'drop_path_prob': 0.3002921064373553, 'grad_clip_value': 6, 'initial_lr': 0.05771836838970096, 'lr_scheduler': 'Exponential', 'optimizer': 'adam', 'weight_decay': 6.844365900915834e-05}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (8, 1, 0) with dispatcher
WARNING:hpbandster:job (8, 1, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (9, 0, 0)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 93, 'drop_path_prob': 0.010135606159188805, 'grad_clip_value': 5, 'initial_lr': 0.0023295147242398877, 'lr_scheduler': 'Exponential', 'optimizer': 'adad', 'weight_decay': 0.000122947610972943}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (9, 0, 0) with dispatcher
WARNING:hpbandster:job (9, 0, 0) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: start processing job (9, 0, 1)
INFO:root:Running config for 6.0 epochs
INFO:root:gpu device = cuda:0
INFO:root:config = {'dense_units': 196, 'drop_path_prob': 0.3937936913923946, 'grad_clip_value': 6, 'initial_lr': 0.02304392722530586, 'lr_scheduler': 'Exponential', 'optimizer': 'adad', 'weight_decay': 0.00047575105327624524}
INFO:hpbandster.run_1.worker.metagpu5.23566:WORKER: registered result for job (9, 0, 1) with dispatcher
WARNING:hpbandster:job (9, 0, 1) failed with exception
Traceback (most recent call last):
  File "/home/rkohli/anaconda3/lib/python3.7/site-packages/hpbandster/core/worker.py", line 206, in start_computation
    result = {'result': self.compute(*args, config_id=id, **kwargs),
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 94, in compute
    ensemble_model = EnsembleModel(self.trained_models, dense_units=config['dense_units'], out_size=self.train_dataset.n_classes)
NameError: name 'EnsembleModel' is not defined

INFO:hpbandster:DISPATCHER: Dispatcher shutting down
INFO:hpbandster:DISPATCHER: shut down complete
Traceback (most recent call last):
  File "main.py", line 281, in <module>
    ensemble_config = run_bohb_ensemble(exp_name=1, model_description=model_description, iterations=10)
  File "/home/rkohli/aml-project/src/bohb_ensemble.py", line 227, in run_bohb_ensemble
    best_config = id2conf[best_run]['config']
KeyError: None
