INFO:root:gpu device = cuda:0
INFO:root:epoch 0 lr 4.442566e-02
INFO:root:Epoch [1/20]
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    save_model_str=get('run_dir'))
  File "main.py", line 341, in create_run_ensemble_self
    train_score, train_loss, models_avg = ensemble_model.train_fn(optimizer, train_criterion, train_loader, device)
NameError: name 'train_criterion' is not defined
